# Generated by Django 6.0 on 2025-12-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('Elf', 'Elegant forest people'), ('Dwarf', 'Dwellers of the underground'), ('Human', 'Most populated race yet the most simple'), ('Ork', 'Mightiest fighters')], max_length=255, unique=True),
        ),
    ]
