# Generated by Django 6.0 on 2025-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(choices=[('elf', 'Elegant forest people'), ('dwarf', 'Dwellers of the underground'), ('human', 'Most populated race yet the most simple'), ('ork', 'Mightiest fighters')], max_length=255, unique=True),
        ),
    ]
