# Generated by Django 6.0 on 2025-12-05 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_race_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='guild',
            field=models.ForeignKey(default='No Guild', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='db.guild'),
        ),
    ]
